# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Duke TxBio
tagline:          translational data science @duke
url:              http://duke-translational-bioinformatics.github.io
paginate:         1
baseurl:          http://duke-translational-bioinformatics.github.io/
author:
  name:           Erich S. Huang, MD/PhD
  url:            
  email:          erich.huang@duke.edu

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/duke-translational-bioinformatics/duke-translational-bioinformatics.github.io
